package ru.chekskan;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.widget.*;import androidx.annotation.Nullable;import androidx.core.content.FileProvider;import com.googlecode.tesseract.android.TessBaseAPI;import java.io.*;import java.text.*;import java.util.*;import java.util.regex.*;

public class MainActivity extends Activity{
 static final int CAMERA=10,GALLERY=11; TextView status,result,currentTotal,monthTotal;EditText dateEdit,storeEdit;Uri photo;ArrayList<Item> items=new ArrayList<>();SimpleDateFormat df=new SimpleDateFormat("dd.MM.yyyy",Locale.US);
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);status=findViewById(R.id.status);result=findViewById(R.id.result);currentTotal=findViewById(R.id.currentTotal);monthTotal=findViewById(R.id.monthTotal);dateEdit=findViewById(R.id.dateEdit);storeEdit=findViewById(R.id.storeEdit);findViewById(R.id.scanButton).setOnClickListener(v->camera());findViewById(R.id.galleryButton).setOnClickListener(v->gallery());findViewById(R.id.manualButton).setOnClickListener(v->manual());findViewById(R.id.saveButton).setOnClickListener(v->saveReceipt());findViewById(R.id.historyButton).setOnClickListener(v->history());findViewById(R.id.exportButton).setOnClickListener(v->exportCsv());findViewById(R.id.deleteButton).setOnClickListener(v->deleteRecord());clear();dashboard();}
 void camera(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.CAMERA},CAMERA);return;}try{File d=new File(getExternalFilesDir(Environment.DIRECTORY_PICTURES),"receipts");d.mkdirs();File f=new File(d,"r_"+System.currentTimeMillis()+".jpg");photo=FileProvider.getUriForFile(this,getPackageName()+".fileprovider",f);Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);i.putExtra(MediaStore.EXTRA_OUTPUT,photo);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);startActivityForResult(i,CAMERA);}catch(Exception e){toast(e.getMessage());}}
 void gallery(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivityForResult(i,GALLERY);}
 @Override protected void onActivityResult(int r,int c,@Nullable Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK)return;try{Uri u=r==CAMERA?photo:d.getData();ocr(MediaStore.Images.Media.getBitmap(getContentResolver(),u));}catch(Exception e){status.setText("Не удалось открыть чек");}}
 void ocr(Bitmap src){status.setText("Распознаю русский текст…");Bitmap b=prep(src);new Thread(()->{try{File base=new File(getFilesDir(),"tesseract"),td=new File(base,"tessdata");td.mkdirs();copy("tessdata/rus.traineddata",new File(td,"rus.traineddata"));copy("tessdata/eng.traineddata",new File(td,"eng.traineddata"));TessBaseAPI t=new TessBaseAPI();if(!t.init(base.getAbsolutePath(),"rus+eng"))throw new Exception();String best="";for(int p:new int[]{4,6,11}){t.setPageSegMode(p);t.setImage(b);String x=t.getUTF8Text();if(x!=null&&x.length()>best.length())best=x;}t.release();String x=best;runOnUiThread(()->parse(x));}catch(Exception e){runOnUiThread(()->status.setText("Ошибка OCR"));}}).start();}
 void copy(String a,File f)throws IOException{if(f.exists()&&f.length()>100000)return;try(InputStream i=getAssets().open(a);OutputStream o=new FileOutputStream(f)){byte[] z=new byte[8192];int n;while((n=i.read(z))>0)o.write(z,0,n);}}
 Bitmap prep(Bitmap s){int w=Math.max(1800,s.getWidth()),h=(int)(s.getHeight()*w/(double)s.getWidth());Bitmap b=Bitmap.createScaledBitmap(s,w,h,true),g=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(g);Paint p=new Paint();ColorMatrix m=new ColorMatrix();m.setSaturation(0);p.setColorFilter(new android.graphics.ColorMatrixColorFilter(m));c.drawBitmap(b,0,0,p);return g;}
 void parse(String text){items.clear();String d=find(text,"(\\d{2}[./-]\\d{2}[./-](?:\\d{2}|\\d{4}))");dateEdit.setText(d==null?df.format(new Date()):d.replace('/','.').replace('-','.'));storeEdit.setText(store(text));Pattern p=Pattern.compile("^(.+?[А-Яа-яA-Za-zЁё].*?)\\s+(\\d{1,6}[,.]\\d{2})\\s*(?:₽|р|руб)?$",Pattern.CASE_INSENSITIVE);for(String raw:text.split("\\r?\\n")){String s=clean(raw);if(skip(s))continue;Matcher m=p.matcher(s);if(m.find()){double v=num(m.group(2));if(v>0&&v<100000)items.add(new Item(clean(m.group(1)),v,cat(m.group(1))));}}render();}
 String store(String text){for(String s:text.split("\\r?\\n")){s=clean(s);String q=s.toLowerCase(Locale.ROOT);if(s.length()>2&&s.length()<50&&letters(s)&&!q.matches(".*(касса|кассир|чек|инн|адрес|смена|дата|время|фн|фд|фп).*")&&!s.matches(".*\\d{2}[./-]\\d{2}.*"))return s;}return "";}
 boolean skip(String s){String q=s.toLowerCase(Locale.ROOT);return s.length()<3||q.matches(".*(итого|к оплате|налич|безналич|кассир|касса|адрес|фн |фд |фп |налог|ндс|сдача|всего).*");}boolean letters(String s){return s.matches(".*[А-Яа-яA-Za-zЁё].*");}
 String cat(String s){String q=s.toLowerCase(Locale.ROOT).replace('ё','е');if(any(q,"пиво","вино","водк","коньяк","виски","сидр","ром","джин"))return"Алкоголь";if(any(q,"аптек","таблет","лекар","мазь","фарма"))return"Аптека";if(any(q,"билет","метро","автобус","поезд","такси","бензин"))return"Транспорт";if(any(q,"театр","кино","музей","концерт"))return"Развлечения";if(any(q,"молок","хлеб","сыр","мяс","рыб","овощ","фрукт","кефир","масло","яйц"))return"Продукты";return"Прочее";}boolean any(String q,String...a){for(String k:a)if(q.contains(k))return true;return false;}
 void render(){StringBuilder b=new StringBuilder();double t=0;for(Item a:items){b.append("• ").append(a.name).append(" — ").append(fmt(a.sum)).append(" ₽ [").append(a.cat).append("]\n");t+=a.sum;}result.setText(items.isEmpty()?"Позиции не найдены — попробуйте другое фото.":b.toString());currentTotal.setText("Сумма чека: "+fmt(t)+" ₽");status.setText("Распознано позиций: "+items.size());}
 void saveReceipt(){if(items.isEmpty()){toast("В окне формирования нет чека");return;}String d=clean(dateEdit.getText().toString());if(d.isEmpty())d=df.format(new Date());String s=clean(storeEdit.getText().toString());if(s.isEmpty())s="Магазин";double t=0;for(Item i:items)t+=i.sum;addRecord(d,s,"Чек",t);toast("Чек сохранён");clear();dashboard();}
 void manual(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText n=new EditText(this),v=new EditText(this),d=new EditText(this);n.setHint("Название расхода");v.setHint("Сумма");v.setInputType(2|8192);d.setText(df.format(new Date()));d.setHint("Дата");box.addView(n);box.addView(v);box.addView(d);new AlertDialog.Builder(this).setTitle("Расход без чека").setView(box).setPositiveButton("Сохранить",(x,w)->{double z=num(v.getText().toString());if(clean(n.getText().toString()).isEmpty()||z<=0){toast("Укажите название и сумму");return;}addRecord(clean(d.getText().toString()),clean(n.getText().toString()),"Без чека",z);dashboard();}).setNegativeButton("Отмена",null).show();}
 void addRecord(String d,String s,String src,double t){String old=getPreferences(0).getString("records","");String row=safe(d)+"\t"+safe(s)+"\t"+safe(src)+"\t"+t;getPreferences(0).edit().putString("records",old.isEmpty()?row:old+"\n"+row).apply();}
 ArrayList<Record> records(){ArrayList<Record>a=new ArrayList<>();String x=getPreferences(0).getString("records","");if(x.isEmpty())return a;for(String r:x.split("\\n")){String[]p=r.split("\\t");if(p.length==4)try{a.add(new Record(p[0],p[1],p[2],Double.parseDouble(p[3])));}catch(Exception e){}}return a;}
 void dashboard(){Calendar now=Calendar.getInstance();double t=0;for(Record r:records())try{Date d=df.parse(r.date);Calendar c=Calendar.getInstance();c.setTime(d);if(c.get(1)==now.get(1)&&c.get(2)==now.get(2))t+=r.total;}catch(Exception e){}monthTotal.setText("Расходы за месяц: "+fmt(t)+" ₽");}
 void history(){ArrayList<Record>a=records();if(a.isEmpty()){toast("История пока пуста");return;}StringBuilder b=new StringBuilder();for(int i=a.size()-1;i>=0;i--){Record r=a.get(i);b.append(r.date).append(" • ").append(r.store).append("\n").append(r.source).append(" — ").append(fmt(r.total)).append(" ₽\n\n");}new AlertDialog.Builder(this).setTitle("История расходов").setMessage(b.toString()).setPositiveButton("Закрыть",null).show();}
 void deleteRecord(){ArrayList<Record>a=records();if(a.isEmpty()){toast("Удалять нечего");return;}String[]n=new String[a.size()];for(int j=0;j<a.size();j++){Record r=a.get(a.size()-1-j);n[j]=r.date+" • "+r.store+" • "+fmt(r.total)+" ₽";}new AlertDialog.Builder(this).setTitle("Удалить запись").setItems(n,(d,w)->{a.remove(a.size()-1-w);StringBuilder b=new StringBuilder();for(Record r:a){if(b.length()>0)b.append("\n");b.append(safe(r.date)).append("\t").append(safe(r.store)).append("\t").append(safe(r.source)).append("\t").append(r.total);}getPreferences(0).edit().putString("records",b.toString()).apply();dashboard();toast("Запись удалена");}).setNegativeButton("Отмена",null).show();}
 void exportCsv(){ArrayList<Record>a=records();if(a.isEmpty()){toast("Нет данных для экспорта");return;}try{File f=new File(getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS),"Kontrol_rashodov_"+System.currentTimeMillis()+".csv");try(PrintWriter p=new PrintWriter(new OutputStreamWriter(new FileOutputStream(f),"UTF-8"))){p.println("Дата;Магазин/расход;Источник;Сумма");for(Record r:a)p.println(r.date+";"+r.store+";"+r.source+";"+fmt(r.total));}toast("Экспорт сохранён в Documents");}catch(Exception e){toast("Ошибка экспорта");}}
 void clear(){items.clear();dateEdit.setText("");storeEdit.setText("");result.setText("Чек пока не добавлен");currentTotal.setText("Сумма чека: 0,00 ₽");status.setText("Добавьте чек камерой или из галереи");}
 String safe(String s){return clean(s).replace('\t',' ').replace('\n',' ');}String clean(String s){return s==null?"":s.trim().replaceAll("\\s{2,}"," ");}double num(String s){try{return Double.parseDouble(s.replace(',','.'));}catch(Exception e){return 0;}}String find(String s,String r){Matcher m=Pattern.compile(r).matcher(s);return m.find()?m.group(1):null;}String fmt(double x){return String.format(Locale.US,"%.2f",x).replace('.',',');}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
 static class Item{String name,cat;double sum;Item(String n,double s,String c){name=n;sum=s;cat=c;}}static class Record{String date,store,source;double total;Record(String d,String s,String x,double t){date=d;store=s;source=x;total=t;}}
}